import type { Profile } from './types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: '1',
    name: 'Sofia',
    age: 27,
    location: 'Brooklyn, NY',
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&q=80',
    ],
    attachmentStyle: 'secure',
    bio: 'Therapist by day, amateur ceramicist by evening. I believe healthy love is built, not found.',
    prompts: [
      { question: 'The way to my heart is…', answer: 'Thoughtful texts at random hours and really good coffee.' },
      { question: 'I\'m looking for…', answer: 'Someone who can sit in comfortable silence and then talk for hours.' },
      { question: 'My attachment style means…', answer: 'I show up consistently and expect the same. No games, just real connection.' },
    ],
    interests: ['Ceramics', 'Hiking', 'Psychology', 'Jazz', 'Cooking'],
    height: '5\'6"',
    pronouns: 'She/Her',
    job: 'Therapist',
    education: 'Columbia University',
  },
  {
    id: '2',
    name: 'Marcus',
    age: 30,
    location: 'Manhattan, NY',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80',
    ],
    attachmentStyle: 'anxious',
    bio: 'Writer and chronic overthinker. I feel things deeply — that\'s both my superpower and my kryptonite.',
    prompts: [
      { question: 'A green flag I look for…', answer: 'When someone remembers the small things I mentioned weeks ago.' },
      { question: 'I\'m working on…', answer: 'Not reading into every "delivered" notification. Baby steps.' },
      { question: 'The best relationship I can imagine…', answer: 'Morning coffee texts, zero guessing games, and someone who stays.' },
    ],
    interests: ['Writing', 'Film', 'Running', 'Philosophy', 'Music'],
    height: '6\'0"',
    pronouns: 'He/Him',
    job: 'Novelist',
    education: 'NYU',
  },
  {
    id: '3',
    name: 'Elena',
    age: 29,
    location: 'Williamsburg, NY',
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=80',
      'https://images.unsplash.com/photo-1504703395950-b89145a5425b?w=600&q=80',
    ],
    attachmentStyle: 'avoidant',
    bio: 'Architect who builds structures for a living and walls around herself occasionally. Working on that.',
    prompts: [
      { question: 'I know it\'s serious when…', answer: 'I give you my actual phone number instead of my Google Voice.' },
      { question: 'My love language is…', answer: 'Acts of service. Words feel vulnerable — I show up instead.' },
      { question: 'What I\'ve learned about myself…', answer: 'I need space to process, but I always come back. Patience is appreciated.' },
    ],
    interests: ['Architecture', 'Bouldering', 'Meditation', 'Solo travel', 'Photography'],
    height: '5\'7"',
    pronouns: 'She/Her',
    job: 'Architect',
    education: 'Pratt Institute',
  },
  {
    id: '4',
    name: 'James',
    age: 32,
    location: 'Park Slope, NY',
    photos: [
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&q=80',
      'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=600&q=80',
    ],
    attachmentStyle: 'secure',
    bio: 'ER doctor. I\'ve learned that presence — real, full presence — is the most healing thing you can give someone.',
    prompts: [
      { question: 'The relationship I\'m looking for…', answer: 'One where we both choose each other on hard days, not just easy ones.' },
      { question: 'A non-negotiable for me…', answer: 'Curiosity. About the world, about each other, about growing together.' },
      { question: 'I find therapy…', answer: 'Fascinating and essential. I\'ve done my work. Let\'s talk about yours.' },
    ],
    interests: ['Medicine', 'Rock climbing', 'Cooking', 'Neuroscience', 'Travel'],
    height: '6\'1"',
    pronouns: 'He/Him',
    job: 'Emergency Physician',
    education: 'Johns Hopkins',
  },
  {
    id: '5',
    name: 'Nia',
    age: 26,
    location: 'Harlem, NY',
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80',
      'https://images.unsplash.com/photo-1494959764136-6be9eb3c261e?w=600&q=80',
    ],
    attachmentStyle: 'disorganized',
    bio: 'Artist and trauma-informed coach. I\'m doing the messy, brave work of healing — and I\'m proud of how far I\'ve come.',
    prompts: [
      { question: 'The most growth I\'ve done…', answer: 'Learning that wanting love AND fearing it can be true at the same time.' },
      { question: 'What I offer in a relationship…', answer: 'The deepest empathy you\'ve ever felt. I understand complexity.' },
      { question: 'Therapy has taught me…', answer: 'My reactions aren\'t who I am — they\'re a map of what I survived.' },
    ],
    interests: ['Painting', 'Somatic therapy', 'Poetry', 'Pilates', 'Tarot'],
    height: '5\'5"',
    pronouns: 'She/Her',
    job: 'Artist & Coach',
    education: 'RISD',
  },
  {
    id: '6',
    name: 'Leo',
    age: 28,
    location: 'Astoria, NY',
    photos: [
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80',
    ],
    attachmentStyle: 'anxious',
    bio: 'Chef who pours love into food. I\'m an affectionate, expressive person looking for someone who won\'t run from that.',
    prompts: [
      { question: 'My biggest green flag…', answer: 'I will always tell you how I feel. No silence, no cold shoulders.' },
      { question: 'What I\'m healing from…', answer: 'Relationships where I had to shrink to feel wanted. Never again.' },
      { question: 'A perfect Sunday is…', answer: 'Farmer\'s market, cooking something new together, no phones after 3pm.' },
    ],
    interests: ['Cooking', 'Farmers markets', 'Language learning', 'Yoga', 'Documentaries'],
    height: '5\'11"',
    pronouns: 'He/Him',
    job: 'Executive Chef',
    education: 'CIA',
  },
  {
    id: '7',
    name: 'Zara',
    age: 31,
    location: 'Upper West Side, NY',
    photos: [
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&q=80',
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80',
    ],
    attachmentStyle: 'secure',
    bio: 'Startup founder and mindful lover of life. I\'ve done the inner work and I\'m ready to build something real.',
    prompts: [
      { question: 'I believe love is…', answer: 'A daily practice, not just a feeling. I show up for it.' },
      { question: 'Something I\'ve learned…', answer: 'Boundaries aren\'t walls. They\'re the architecture of a healthy relationship.' },
      { question: 'I\'m drawn to people who…', answer: 'Know themselves. Not perfectly — just honestly.' },
    ],
    interests: ['Tech', 'Meditation', 'Books', 'Tennis', 'Travel'],
    height: '5\'8"',
    pronouns: 'She/Her',
    job: 'Startup Founder',
    education: 'Stanford',
  },
  {
    id: '8',
    name: 'Theo',
    age: 33,
    location: 'Greenwich Village, NY',
    photos: [
      'https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80',
      'https://images.unsplash.com/photo-1456327102063-fb5054efe647?w=600&q=80',
    ],
    attachmentStyle: 'avoidant',
    bio: 'Philosophy professor who is slowly learning that thinking about love and being in love are very different things.',
    prompts: [
      { question: 'The best description of me…', answer: 'Quietly devoted. I show love through reliability, not grand gestures.' },
      { question: 'I\'m drawn to people who…', answer: 'Don\'t need me to be everything. I can be a lot — just not everything.' },
      { question: 'One thing I\'m unlearning…', answer: 'That vulnerability is weakness. It\'s terrifying, but I\'m trying.' },
    ],
    interests: ['Philosophy', 'Chess', 'Long walks', 'Jazz', 'Wine'],
    height: '6\'2"',
    pronouns: 'He/Him',
    job: 'Professor',
    education: 'Yale',
  },
];

export const PROMPT_OPTIONS = [
  'The way to my heart is…',
  'I\'m looking for…',
  'A green flag I look for…',
  'I\'m working on…',
  'My love language is…',
  'The relationship I\'m looking for…',
  'My attachment style means…',
  'Something I\'ve learned about myself…',
  'A non-negotiable for me…',
  'The most growth I\'ve done…',
  'I find therapy…',
  'I know it\'s serious when…',
  'A perfect Sunday is…',
  'The best relationship I can imagine…',
];

export const INTEREST_OPTIONS = [
  'Hiking', 'Cooking', 'Travel', 'Reading', 'Music', 'Yoga', 'Photography',
  'Art', 'Film', 'Running', 'Rock climbing', 'Meditation', 'Writing', 'Dance',
  'Therapy', 'Podcasts', 'Cycling', 'Swimming', 'Coffee', 'Brunch',
];
